"""
Enterprise EHSQ accounts — all confirmed in OSHA inspection CSV data (2015+).
Inspection counts as of June 2026 across 5M+ federal OSHA records.
osha_search terms match on ESTAB_NAME (partial, case-insensitive LIKE).
cms_search terms match on provider_name in CMS Health Deficiencies dataset (nursing homes only).
"""

ACCOUNTS = [

    # ── Logistics / Transportation ───────────────────────────────────────────

    {
        "id": "ups",
        "name": "United Parcel Service (UPS)",
        "group": "SE",
        "child": False,
        "customer": False,
        "segment": ["logistics", "enterprise"],
        "owner": "",
        "crm_connected": False,
        "osha_confirmed": True,
        "osha_search": ["United Parcel Service"],
        "cms_search": [],
        "hq_state": "GA",
        "website": "",
        "description": "World's largest package delivery company, 500K+ employees. 1,200+ OSHA inspections across all 50 states. Major EHS software buyer.",
    },
    {
        "id": "amazon",
        "name": "Amazon (Fulfillment & Logistics)",
        "group": "NW",
        "child": False,
        "customer": False,
        "segment": ["logistics", "enterprise"],
        "owner": "",
        "crm_connected": False,
        "osha_confirmed": True,
        "osha_search": ["Amazon.com Services", "Amazon Fulfillment", "Amazon Logistics"],
        "cms_search": [],
        "hq_state": "WA",
        "website": "",
        "description": "Largest US fulfillment network, 1M+ warehouse employees. 467+ OSHA inspections. Under heavy regulatory scrutiny for workplace safety.",
    },
    {
        "id": "fedex",
        "name": "FedEx Corporation",
        "group": "SE",
        "child": False,
        "customer": False,
        "segment": ["logistics", "enterprise"],
        "owner": "",
        "crm_connected": False,
        "osha_confirmed": True,
        "osha_search": ["Federal Express", "FedEx Ground", "FedEx Express", "FedEx Freight"],
        "cms_search": [],
        "hq_state": "TN",
        "website": "",
        "description": "Global logistics, 500K+ employees across Express, Ground, and Freight divisions. 616+ OSHA inspections.",
    },
    {
        "id": "southwest-airlines",
        "name": "Southwest Airlines",
        "group": "SW",
        "child": False,
        "customer": False,
        "segment": ["logistics", "enterprise"],
        "owner": "",
        "crm_connected": False,
        "osha_confirmed": True,
        "osha_search": ["Southwest Airlines"],
        "cms_search": [],
        "hq_state": "TX",
        "website": "",
        "description": "Largest US domestic airline, 60K+ employees. 101+ OSHA inspections. Aviation safety and ground ops EHS requirements.",
    },
    {
        "id": "american-airlines",
        "name": "American Airlines",
        "group": "SW",
        "child": False,
        "customer": False,
        "segment": ["logistics", "enterprise"],
        "owner": "",
        "crm_connected": False,
        "osha_confirmed": True,
        "osha_search": ["American Airlines"],
        "cms_search": [],
        "hq_state": "TX",
        "website": "",
        "description": "World's largest airline by fleet size, 130K+ employees. 115+ OSHA inspections across maintenance, ramp, and ground ops.",
    },
    {
        "id": "americold",
        "name": "Americold Logistics",
        "group": "SE",
        "child": False,
        "customer": False,
        "segment": ["logistics", "enterprise"],
        "owner": "",
        "crm_connected": False,
        "osha_confirmed": True,
        "osha_search": ["Americold Logistics", "Americold"],
        "cms_search": [],
        "hq_state": "GA",
        "website": "",
        "description": "World's largest temperature-controlled warehouse REIT, 250+ facilities. 186+ OSHA inspections. Cold chain safety is a major compliance area.",
    },
    {
        "id": "dhl",
        "name": "DHL Supply Chain",
        "group": "MW",
        "child": False,
        "customer": False,
        "segment": ["logistics", "enterprise"],
        "owner": "",
        "crm_connected": False,
        "osha_confirmed": True,
        "osha_search": ["DHL Supply Chain", "DHL"],
        "cms_search": [],
        "hq_state": "OH",
        "website": "",
        "description": "DHL's US contract logistics arm, 50K+ employees across 400+ warehouses. 92+ OSHA inspections.",
    },

    # ── Food & Beverage Manufacturing ────────────────────────────────────────

    {
        "id": "tyson-foods",
        "name": "Tyson Foods",
        "group": "SW",
        "child": False,
        "customer": False,
        "segment": ["manufacturing", "enterprise"],
        "owner": "",
        "crm_connected": False,
        "osha_confirmed": True,
        "osha_search": ["Tyson Foods", "Tyson Fresh Meats"],
        "cms_search": [],
        "hq_state": "AR",
        "website": "",
        "description": "Largest US meat processor, 120K+ employees. 359+ OSHA inspections. High-risk food processing environments with major EHS compliance exposure.",
    },
    {
        "id": "pilgrims-pride",
        "name": "Pilgrim's Pride Corporation",
        "group": "SW",
        "child": False,
        "customer": False,
        "segment": ["manufacturing", "enterprise"],
        "owner": "",
        "crm_connected": False,
        "osha_confirmed": True,
        "osha_search": ["Pilgrim's Pride", "Pilgrims Pride"],
        "cms_search": [],
        "hq_state": "CO",
        "website": "",
        "description": "Second-largest US chicken producer, 60K+ employees. 108+ OSHA inspections across poultry processing plants.",
    },
    {
        "id": "bimbo-bakeries",
        "name": "Bimbo Bakeries USA",
        "group": "NE",
        "child": False,
        "customer": False,
        "segment": ["manufacturing", "enterprise"],
        "owner": "",
        "crm_connected": False,
        "osha_confirmed": True,
        "osha_search": ["Bimbo Bakeries USA", "Bimbo Bakeries"],
        "cms_search": [],
        "hq_state": "PA",
        "website": "",
        "description": "Largest US baked goods company (Entenmann's, Sara Lee, Thomas'), 20K+ employees. 215+ OSHA inspections.",
    },
    {
        "id": "smithfield-foods",
        "name": "Smithfield Foods",
        "group": "SE",
        "child": False,
        "customer": False,
        "segment": ["manufacturing", "enterprise"],
        "owner": "",
        "crm_connected": False,
        "osha_confirmed": True,
        "osha_search": ["Smithfield Foods", "Smithfield"],
        "cms_search": [],
        "hq_state": "VA",
        "website": "",
        "description": "World's largest pork processor, 40K+ US employees. 84+ OSHA inspections. High EHS exposure in meat processing.",
    },

    # ── Industrial Manufacturing ──────────────────────────────────────────────

    {
        "id": "international-paper",
        "name": "International Paper",
        "group": "SE",
        "child": False,
        "customer": False,
        "segment": ["manufacturing", "enterprise"],
        "owner": "",
        "crm_connected": False,
        "osha_confirmed": True,
        "osha_search": ["International Paper"],
        "cms_search": [],
        "hq_state": "TN",
        "website": "",
        "description": "World's largest paper and packaging company, 65K employees, 150+ mills globally. 238+ OSHA inspections.",
    },
    {
        "id": "tesla",
        "name": "Tesla, Inc.",
        "group": "SW",
        "child": False,
        "customer": False,
        "segment": ["manufacturing", "enterprise"],
        "owner": "",
        "crm_connected": False,
        "osha_confirmed": True,
        "osha_search": ["Tesla, Inc.", "Tesla Inc", "Tesla"],
        "cms_search": [],
        "hq_state": "TX",
        "website": "",
        "description": "EV/energy manufacturing, Gigafactories across TX, NV, CA, NY. 228+ OSHA inspections. Under sustained OSHA scrutiny for injury reporting.",
    },
    {
        "id": "ford-motor",
        "name": "Ford Motor Company",
        "group": "MW",
        "child": False,
        "customer": False,
        "segment": ["manufacturing", "enterprise"],
        "owner": "",
        "crm_connected": False,
        "osha_confirmed": True,
        "osha_search": ["Ford Motor Company", "Ford Motor"],
        "cms_search": [],
        "hq_state": "MI",
        "website": "",
        "description": "Major US automaker, 170K+ employees, assembly plants across MI, KY, MO, IL. 165+ OSHA inspections.",
    },
    {
        "id": "caterpillar",
        "name": "Caterpillar Inc.",
        "group": "MW",
        "child": False,
        "customer": False,
        "segment": ["manufacturing", "enterprise"],
        "owner": "",
        "crm_connected": False,
        "osha_confirmed": True,
        "osha_search": ["Caterpillar Inc", "Caterpillar"],
        "cms_search": [],
        "hq_state": "IL",
        "website": "",
        "description": "World's largest construction/mining equipment manufacturer, 100K+ employees. 105+ OSHA inspections across IL, IN, KY, MI, OH plants.",
    },

    # ── Energy & Utilities ────────────────────────────────────────────────────

    {
        "id": "chevron",
        "name": "Chevron U.S.A.",
        "group": "NW",
        "child": False,
        "customer": False,
        "segment": ["energy", "enterprise"],
        "owner": "",
        "crm_connected": False,
        "osha_confirmed": True,
        "osha_search": ["Chevron U.S.A", "Chevron USA"],
        "cms_search": [],
        "hq_state": "CA",
        "website": "",
        "description": "Major integrated energy company, refineries in CA, MS, TX. 68+ OSHA inspections. Process safety management is a core EHS requirement.",
    },
    {
        "id": "phillips-66",
        "name": "Phillips 66",
        "group": "SW",
        "child": False,
        "customer": False,
        "segment": ["energy", "enterprise"],
        "owner": "",
        "crm_connected": False,
        "osha_confirmed": True,
        "osha_search": ["Phillips 66 Company", "Phillips 66"],
        "cms_search": [],
        "hq_state": "TX",
        "website": "",
        "description": "Major US refining/midstream/chemicals, 14 refineries across CA, IL, LA, TX, MT. 106+ OSHA inspections.",
    },
    {
        "id": "pacific-gas-electric",
        "name": "Pacific Gas & Electric (PG&E)",
        "group": "NW",
        "child": False,
        "customer": False,
        "segment": ["utilities", "enterprise"],
        "owner": "",
        "crm_connected": False,
        "osha_confirmed": True,
        "osha_search": ["Pacific Gas and Electric", "Pacific Gas & Electric", "PG&E"],
        "cms_search": [],
        "hq_state": "CA",
        "website": "",
        "description": "California's largest utility, 71K employees, under intense post-wildfire regulatory pressure. 87+ OSHA inspections. Strong EHSQ software buyer.",
    },

    # ── Healthcare ────────────────────────────────────────────────────────────

    {
        "id": "kaiser-permanente",
        "name": "Kaiser Permanente",
        "group": "NW",
        "child": False,
        "customer": False,
        "segment": ["healthcare", "enterprise"],
        "owner": "",
        "crm_connected": False,
        "osha_confirmed": True,
        "osha_search": ["Kaiser Foundation", "Kaiser Permanente"],
        "cms_search": ["KAISER PERMANENTE", "KAISER FOUNDATION"],
        "hq_state": "CA",
        "website": "",
        "description": "Largest managed care org in the US, 40+ hospitals, 700+ clinics, 300K+ employees. 174+ OSHA inspections across CA, CO, DC, HI, MD, OR, VA.",
    },
    {
        "id": "veterans-affairs",
        "name": "Department of Veterans Affairs (VA)",
        "group": "FED",
        "child": False,
        "customer": False,
        "segment": ["healthcare", "gov"],
        "owner": "",
        "crm_connected": False,
        "osha_confirmed": True,
        "osha_search": ["Veterans Affairs", "Dept of Veterans Affairs", "Department of Veterans Affairs", "VA Medical Center", "VAMC"],
        "cms_search": ["VETERANS AFFAIRS", "VA MEDICAL CENTER"],
        "hq_state": "DC",
        "website": "",
        "description": "Federal healthcare system, 170+ VA medical centers nationwide, 400K+ employees. 666+ OSHA inspections across all states.",
    },
    {
        "id": "dignity-health",
        "name": "Dignity Health (CommonSpirit)",
        "group": "NW",
        "child": False,
        "customer": False,
        "segment": ["healthcare", "enterprise"],
        "owner": "",
        "crm_connected": False,
        "osha_confirmed": True,
        "osha_search": ["Dignity Health", "CommonSpirit"],
        "cms_search": ["DIGNITY HEALTH", "COMMONSPIRIT"],
        "hq_state": "CA",
        "website": "",
        "description": "Dignity Health is the western US arm of CommonSpirit Health, 40+ hospitals across AZ, CA, NV. 74+ OSHA inspections.",
    },
]


def get_all_accounts():
    return ACCOUNTS

def get_account_by_id(account_id: str):
    return next((a for a in ACCOUNTS if a["id"] == account_id), None)
